### ISSUE TITLE
An actual ending? Or a game in perpetual progress, with no ultimate pay-off in sight?

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#10]
If we don't set a deadline for a big ending to at least be decided upon, would we ever complete the game?

**Comment by DarkLizerd** [comment]
Most likely not, because someone (me maybe) will have that one last must add tweak... Followed by the tweak that fixed the last tweak...
We can't set the final version for 1 year out, too much could happen, like loosing a programmer, or life getting in the way, but, we can't set it to 30 days or die trying either...
Professional programmers set a date so that the game can be released and so they can get paid for their work. Working for free anyway, we don't have that pressure and hopefully we will not release buggy software that "will be fixed with a patch" later... then the update, followed by the patch that fixes the update...
We will just need to follow this by ear until we get close to a "release date".

**Comment by hegemonkhan** [comment]
I personally hate open-endings (huge pet peeve of mine), where it's up to you to decide/analyze/debate/discuss/interprete on what the ending is. If I play or read something to its end, I'm obviously interested in it, and thus I want to know exactly how the story ends! I hate having an ambigious ending.

---------

Endings are definately important, as it helps guide everything else: you got a destination/goal to connect up with.

-----------

as for expanding the game further:

having endings actually work well for this, as that "game ending" could just be a "benchmark" within the game (as we expand it further) and/or just the end of a "chapter/arc" of our expanded game.

this way, by having endings, we'll always have a complete game, but can always expand our game too.

**Comment by rheadkid** [comment]
I've never,ever written an ending <del>I was happy with</del> with which I was happy. 

Of course, I'm rarely impressed with ANY ending that doesn't come out of nowhere while still being inescapably explicable.

(And there went my two 5-cent words for today!)

**Comment by rheadkid** [comment]
May open again at a later date
