### ISSUE TITLE
an NPC who shows up, then dies, in nearly every region?

### ISSUE THREAD

**Issue by rheadkid** [rheadkid/Quest-Group_Project#8]
Can we even gather followers in a region, then have them with us back in the main hub?

**Comment by DarkLizerd** [comment]
Most likely not, then every world will need to take into account that army of 15 orc knights you have acquired. 
Altho, a "red shirt" comic relief could be fun... 
"OH, NO!!! They killed Kenny!!!" again!

**Comment by hegemonkhan** [comment]
this has been used a lot, but it could be cool:

a guide/helpful npc (your common "wizard" who offers you help/hints in the game, like many old games had), who turns out to be the bad guy you face at the end. We could have death/ferryman of purgatory be this character, being able to briefly show up in the worlds of the living, and uses his death to get back to purgatory.

we could use this for our plot too: death/ferryman wants to escape from purgatory, to destroy/control the worlds, and he's using you, to collect the stuff he needs to finally be free of his prison in purgatory. (Myst has this concept, you collect the missing pages of the books for the bad guys, which you don't know are bad, for them to escape from the books with all of their power, to take over the world)

a very over-used idea... but maybe it could still be cool for this game.

but, you guys can decide if you like it or not.

**Comment by ThePix** [comment]
What and who can be taken from one dimension to another and how we rationalise that is a big issue...

**Comment by rheadkid** [comment]
>What and who can be taken from one dimension to another and how we rationalise that is a big issue...

Good point.

It's probably going to be enough fun filling up plot holes and keeping an eye out for any contradictions once all the tales are woven together.

---
Sort of on topic:

What if carrying certain items out of one dimension triggers a paradox?

Most paradoxes are bad, but one or two could work out in your favor...

**Comment by XanMag** [comment]
I certainly think a character or two from each whatever-world-they-are-from-but-don't-know-what-we-are-calling-it yet (galaxy?) would be interesting especially if referencing their commentary is useful in other galaxies.  Coding for this would be pretty simple as the person who initially wrote the NPC would simply write them in the main hub where they can be made visible after a specific event.

**Comment by rheadkid** [comment]
Why did I thumbs-up both sides of the argument?

All valid points!

But...

closing.

can reopen if everyone votes for it
